apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: milvus-image-name
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    This task will generate an milvus image name.
  params:
  - name: registryToPush
    description: the registry to push
    default: harbor.milvus.io
  - name: runtime_image
    default: alpine:latest
    description: the image of this task
  results:
    - name: name
      description: the generated image name
  steps:
  - name: "generate-image-name"
    image: $(params.runtime_image)
    script: |
      #!/usr/bin/env sh

      # Variable definition
      registryToPush=$(params.registryToPush)

      name=""

      # Assign your variable value here for testing purposes
      # registryToPush="harbor.milvus.io"

      # Check the value of registryToPush and output the appropriate string
      if [ "$registryToPush" = "harbor.milvus.io" ]; then
        name="harbor.milvus.io/milvusdb/milvus"
      elif [ "$registryToPush" = "docker.io" ]; then
        name="milvusdb/milvus"
      else
        echo "invalid registry"
        exit 1
      fi

      echo -n "${name}" >  $(results.name.path)

      echo "image name: ${name}"




