apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-tag
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: >-
    This task will generate an image tag.
  params:
  - name: branch
    description: the branch name of the source code.
    default: "master"
  - name: hash
    description: the hash code of the current commit.
  - name: arch
    description: the architectures of the image, it would be amd64 or arm64
    default: "amd64"
  - name: computing_engine
    default: "cpu"
  - name: runtime_image
    default: alpine:latest
    description: the image of this task
  results:
    - name: tag 
      description: the generated image tag
    - name: hash
      description: the shorten hash code of the current commit.
    - name: timestamp
      description: The current timestamp
  steps:
  - name: "generate-tag"
    image: $(params.runtime_image)
    script: |
      #!/usr/bin/env sh
      current=$(date +%Y%m%d)
      hash=$(echo $(params.hash) | cut -c1-8 )
      tag="$(params.branch)-${current}-${hash}"

      arch=$(params.arch)

      # if it is building gpu image, append
      # gpu into tag
      if [ "$(params.computing_engine)" = "gpu" ]; then
        tag="${tag}-gpu"
      fi

      if [ -n "$arch" ]; then
        tag="${tag}-${arch}"
      fi

      echo "tag: ${tag}"

      echo -n "${current}" > $(results.timestamp.path)
      echo -n "${hash}" > $(results.hash.path)
      echo -n "${tag}" >  $(results.tag.path)




